volumes:
  redis-data:
    driver: local
  notificacoes-data:

services:
  db:
    image: mysql:8
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notificacoes
      - MYSQL_USER=notificacoes
      - MYSQL_PASSWORD=notificacoes
    volumes:
      - notificacoes-data:/var/lib/mysql:${DELEGATED_VOLUMES:-delegated}
    ports:
      - "3309:3306"

  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORT:-6379}:6389

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - APP_ENV=${APP_ENV:-dev}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - redis
    depends_on:
      - redis
      - db
