version: '3.9'

volumes:
  redis-data:
    driver: local

services:
  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORT:-6379}:6389

  app:
    image: node:20.10-alpine
    working_dir: /app
    command:
      ['/bin/sh', '-c', 'npm install && npm run build && npm run start:dev']
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - redis
    depends_on:
      - redis
